bookwyrm/urls.py
''' url routing for the app and api '''
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, re_path

from bookwyrm import incoming, outgoing, views, settings, wellknown
from bookwyrm import view_actions as actions

username_regex = r'(?P<username>[\w\-_\.]+@[\w\-\_\.]+)'
localname_regex = r'(?P<username>[\w\-_\.]+)'
user_path = r'^user/%s' % username_regex
local_user_path = r'^user/%s' % localname_regex

status_types = [
    'status',
    'review',
    'comment',
    'quotation',
    'boost',
    'generatednote'
]
status_path = r'%s/(%s)/(?P<status_id>\d+)' % \
        (local_user_path, '|'.join(status_types))

book_path = r'^book/(?P<book_id>\d+)'

handler404 = 'bookwyrm.views.not_found_page'
handler500 = 'bookwyrm.views.server_error_page'
urlpatterns = [
    path('admin/', admin.site.urls),

    # federation endpoints
    re_path(r'^inbox/?$', incoming.shared_inbox),
    re_path(r'%s/inbox/?$' % local_user_path, incoming.inbox),
    re_path(r'%s/outbox/?$' % local_user_path, outgoing.outbox),

    # .well-known endpoints
    re_path(r'^.well-known/webfinger/?$', wellknown.webfinger),
    re_path(r'^.well-known/nodeinfo/?$', wellknown.nodeinfo_pointer),
    re_path(r'^nodeinfo/2\.0/?$', wellknown.nodeinfo),
    re_path(r'^api/v1/instance/?$', wellknown.instance_info),
    re_path(r'^api/v1/instance/peers/?$', wellknown.peers),
    # TODO: re_path(r'^.well-known/host-meta/?$', incoming.host_meta),
    # TODO: robots.txt

    # ui views
    re_path(r'^login/?$', views.login_page),
    re_path(r'^about/?$', views.about_page),
    re_path(r'^password-reset/?$', views.password_reset_request),
    re_path(r'^password-reset/(?P<code>[A-Za-z0-9]+)/?$', views.password_reset),
    re_path(r'^invite/?$', views.manage_invites),
    re_path(r'^invite/(?P<code>[A-Za-z0-9]+)/?$', views.invite_page),

    path('', views.home),
    re_path(r'^(?P<tab>home|local|federated)/?$', views.home_tab),
    re_path(r'^notifications/?$', views.notifications_page),
    re_path(r'^direct-messages/?$', views.direct_messages_page),
    re_path(r'^import/?$', views.import_page),
    re_path(r'^import-status/(\d+)/?$', views.import_status),
    re_path(r'^user-edit/?$', views.edit_profile_page),

    # should return a ui view or activitypub json blob as requested
    # users
    re_path(r'%s/?$' % user_path, views.user_page),
    re_path(r'%s\.json$' % local_user_path, views.user_page),
    re_path(r'%s/?$' % local_user_path, views.user_page),
    re_path(r'%s/shelves/?$' % local_user_path, views.user_shelves_page),
    re_path(r'%s/followers(.json)?/?$' % local_user_path, views.followers_page),
    re_path(r'%s/following(.json)?/?$' % local_user_path, views.following_page),

    # statuses
    re_path(r'%s(.json)?/?$' % status_path, views.status_page),
    re_path(r'%s/activity/?$' % status_path, views.status_page),
    re_path(r'%s/replies(.json)?/?$' % status_path, views.replies_page),

    # books
    re_path(r'%s(.json)?/?$' % book_path, views.book_page),
    re_path(r'%s/edit/?$' % book_path, views.edit_book_page),
    re_path(r'%s/editions(.json)?/?$' % book_path, views.editions_page),

    re_path(r'^author/(?P<author_id>[\w\-]+)(.json)?/?$', views.author_page),
    re_path(r'^tag/(?P<tag_id>.+)\.json/?$', views.tag_page),
    re_path(r'^tag/(?P<tag_id>.+)/?$', views.tag_page),
    re_path(r'^%s/shelf/(?P<shelf_identifier>[\w-]+)(.json)?/?$' % \
            user_path, views.shelf_page),
    re_path(r'^%s/shelf/(?P<shelf_identifier>[\w-]+)(.json)?/?$' % \
            local_user_path, views.shelf_page),

    re_path(r'^search/?$', views.search),

    # internal action endpoints
    re_path(r'^logout/?$', actions.user_logout),
    re_path(r'^user-login/?$', actions.user_login),
    re_path(r'^user-register/?$', actions.register),
    re_path(r'^reset-password-request/?$', actions.password_reset_request),
    re_path(r'^reset-password/?$', actions.password_reset),
    re_path(r'^change-password/?$', actions.password_change),

    re_path(r'^edit-profile/?$', actions.edit_profile),

    re_path(r'^import-data/?$', actions.import_data),
    re_path(r'^retry-import/?$', actions.retry_import),
    re_path(r'^resolve-book/?$', actions.resolve_book),
    re_path(r'^edit-book/(?P<book_id>\d+)/?$', actions.edit_book),
    re_path(r'^upload-cover/(?P<book_id>\d+)/?$', actions.upload_cover),
    re_path(r'^add-description/(?P<book_id>\d+)/?$', actions.add_description),

    re_path(r'^switch-edition/?$', actions.switch_edition),
    re_path(r'^edit-readthrough/?$', actions.edit_readthrough),
    re_path(r'^delete-readthrough/?$', actions.delete_readthrough),

    re_path(r'^rate/?$', actions.rate),
    re_path(r'^review/?$', actions.review),
    re_path(r'^quote/?$', actions.quotate),
    re_path(r'^comment/?$', actions.comment),
    re_path(r'^tag/?$', actions.tag),
    re_path(r'^untag/?$', actions.untag),
    re_path(r'^reply/?$', actions.reply),

    re_path(r'^favorite/(?P<status_id>\d+)/?$', actions.favorite),
    re_path(r'^unfavorite/(?P<status_id>\d+)/?$', actions.unfavorite),
    re_path(r'^boost/(?P<status_id>\d+)/?$', actions.boost),
    re_path(r'^unboost/(?P<status_id>\d+)/?$', actions.unboost),

    re_path(r'^delete-status/(?P<status_id>\d+)/?$', actions.delete_status),

    re_path(r'^create-shelf/?$', actions.create_shelf),
    re_path(r'^edit-shelf/(?P<shelf_id>\d+)?$', actions.edit_shelf),
    re_path(r'^delete-shelf/(?P<shelf_id>\d+)?$', actions.delete_shelf),
    re_path(r'^shelve/?$', actions.shelve),
    re_path(r'^unshelve/?$', actions.unshelve),
    re_path(r'^start-reading/(?P<book_id>\d+)/?$', actions.start_reading),
    re_path(r'^finish-reading/(?P<book_id>\d+)/?$', actions.finish_reading),

    re_path(r'^follow/?$', actions.follow),
    re_path(r'^unfollow/?$', actions.unfollow),
    re_path(r'^accept-follow-request/?$', actions.accept_follow_request),
    re_path(r'^delete-follow-request/?$', actions.delete_follow_request),

    re_path(r'^clear-notifications/?$', actions.clear_notifications),

    re_path(r'^create-invite/?$', actions.create_invite),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

celerywyrm/urls.py
from django.contrib import admin
from django.conf.urls.static import static
from django.urls import path

from celerywyrm import settings

urlpatterns = [
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

bookwyrm/models/author.py
''' database schema for info about authors '''
from django.db import models
from django.utils import timezone

from bookwyrm import activitypub
from bookwyrm.settings import DOMAIN

from .base_model import ActivitypubMixin, BookWyrmModel
from . import fields


class Author(ActivitypubMixin, BookWyrmModel):
    ''' basic biographic info '''
    origin_id = models.CharField(max_length=255, null=True)
    openlibrary_key = fields.CharField(
        max_length=255, blank=True, null=True, deduplication_field=True)
    sync = models.BooleanField(default=True)
    last_sync_date = models.DateTimeField(default=timezone.now)
    wikipedia_link = fields.CharField(
        max_length=255, blank=True, null=True, deduplication_field=True)
    # idk probably other keys would be useful here?
    born = fields.DateTimeField(blank=True, null=True)
    died = fields.DateTimeField(blank=True, null=True)
    name = fields.CharField(max_length=255)
    aliases = fields.ArrayField(
        models.CharField(max_length=255), blank=True, default=list
    )
    bio = fields.HtmlField(null=True, blank=True)

    def save(self, *args, **kwargs):
        ''' can't be abstract for query reasons, but you shouldn't USE it '''
        if self.id and not self.remote_id:
            self.remote_id = self.get_remote_id()

        if not self.id:
            self.origin_id = self.remote_id
            self.remote_id = None
        return super().save(*args, **kwargs)

    def get_remote_id(self):
        ''' editions and works both use "book" instead of model_name '''
        return 'https://%s/author/%s' % (DOMAIN, self.id)

    activity_serializer = activitypub.Author

bookwyrm/models/book.py
''' database schema for books and shelves '''
import re

from django.db import models
from django.utils import timezone
from model_utils.managers import InheritanceManager

from bookwyrm import activitypub
from bookwyrm.settings import DOMAIN

from .base_model import BookWyrmModel
from .base_model import ActivitypubMixin, OrderedCollectionPageMixin
from . import fields

class Book(ActivitypubMixin, BookWyrmModel):
    ''' a generic book, which can mean either an edition or a work '''
    origin_id = models.CharField(max_length=255, null=True, blank=True)
    # these identifiers apply to both works and editions
    openlibrary_key = fields.CharField(
        max_length=255, blank=True, null=True, deduplication_field=True)
    librarything_key = fields.CharField(
        max_length=255, blank=True, null=True, deduplication_field=True)
    goodreads_key = fields.CharField(
        max_length=255, blank=True, null=True, deduplication_field=True)

    # info about where the data comes from and where/if to sync
    sync = models.BooleanField(default=True)
    sync_cover = models.BooleanField(default=True)
    last_sync_date = models.DateTimeField(default=timezone.now)
    connector = models.ForeignKey(
        'Connector', on_delete=models.PROTECT, null=True)

    # TODO: edit history

    # book/work metadata
    title = fields.CharField(max_length=255)
    sort_title = fields.CharField(max_length=255, blank=True, null=True)
    subtitle = fields.CharField(max_length=255, blank=True, null=True)
    description = fields.HtmlField(blank=True, null=True)
    languages = fields.ArrayField(
        models.CharField(max_length=255), blank=True, default=list
    )
    series = fields.CharField(max_length=255, blank=True, null=True)
    series_number = fields.CharField(max_length=255, blank=True, null=True)
    subjects = fields.ArrayField(
        models.CharField(max_length=255), blank=True, null=True, default=list
    )
    subject_places = fields.ArrayField(
        models.CharField(max_length=255), blank=True, null=True, default=list
    )
    # TODO: include an annotation about the type of authorship (ie, translator)
    authors = fields.ManyToManyField('Author')
    # preformatted authorship string for search and easier display
    author_text = models.CharField(max_length=255, blank=True, null=True)
    cover = fields.ImageField(
        upload_to='covers/', blank=True, null=True, alt_field='alt_text')
    first_published_date = fields.DateTimeField(blank=True, null=True)
    published_date = fields.DateTimeField(blank=True, null=True)

    objects = InheritanceManager()

    @property
    def edition_info(self):
        ''' properties of this edition, as a string '''
        items = [
            self.physical_format if hasattr(self, 'physical_format') else None,
            self.languages[0] + ' language' if self.languages and \
                    self.languages[0] != 'English' else None,
            str(self.published_date.year) if self.published_date else None,
        ]
        return ', '.join(i for i in items if i)

    @property
    def alt_text(self):
        ''' image alt test '''
        text = '%s cover' % self.title
        if self.edition_info:
            text += ' (%s)' % self.edition_info
        return text

    def save(self, *args, **kwargs):
        ''' can't be abstract for query reasons, but you shouldn't USE it '''
        if not isinstance(self, Edition) and not isinstance(self, Work):
            raise ValueError('Books should be added as Editions or Works')

        if self.id and not self.remote_id:
            self.remote_id = self.get_remote_id()

        if not self.id:
            self.origin_id = self.remote_id
            self.remote_id = None
        return super().save(*args, **kwargs)

    def get_remote_id(self):
        ''' editions and works both use "book" instead of model_name '''
        return 'https://%s/book/%d' % (DOMAIN, self.id)

    def __repr__(self):
        return "<{} key={!r} title={!r}>".format(
            self.__class__,
            self.openlibrary_key,
            self.title,
        )


class Work(OrderedCollectionPageMixin, Book):
    ''' a work (an abstract concept of a book that manifests in an edition) '''
    # library of congress catalog control number
    lccn = fields.CharField(
        max_length=255, blank=True, null=True, deduplication_field=True)
    # this has to be nullable but should never be null
    default_edition = fields.ForeignKey(
        'Edition',
        on_delete=models.PROTECT,
        null=True,
        load_remote=False
    )

    def get_default_edition(self):
        ''' in case the default edition is not set '''
        return self.default_edition or self.editions.first()

    activity_serializer = activitypub.Work
    serialize_reverse_fields = [('editions', 'editions')]
    deserialize_reverse_fields = [('editions', 'editions')]


class Edition(Book):
    ''' an edition of a book '''
    # these identifiers only apply to editions, not works
    isbn_10 = fields.CharField(
        max_length=255, blank=True, null=True, deduplication_field=True)
    isbn_13 = fields.CharField(
        max_length=255, blank=True, null=True, deduplication_field=True)
    oclc_number = fields.CharField(
        max_length=255, blank=True, null=True, deduplication_field=True)
    asin = fields.CharField(
        max_length=255, blank=True, null=True, deduplication_field=True)
    pages = fields.IntegerField(blank=True, null=True)
    physical_format = fields.CharField(max_length=255, blank=True, null=True)
    publishers = fields.ArrayField(
        models.CharField(max_length=255), blank=True, default=list
    )
    shelves = models.ManyToManyField(
        'Shelf',
        symmetrical=False,
        through='ShelfBook',
        through_fields=('book', 'shelf')
    )
    parent_work = fields.ForeignKey(
        'Work', on_delete=models.PROTECT, null=True,
        related_name='editions', activitypub_field='work')

    activity_serializer = activitypub.Edition
    name_field = 'title'

    def save(self, *args, **kwargs):
        ''' calculate isbn 10/13 '''
        if self.isbn_13 and self.isbn_13[:3] == '978' and not self.isbn_10:
            self.isbn_10 = isbn_13_to_10(self.isbn_13)
        if self.isbn_10 and not self.isbn_13:
            self.isbn_13 = isbn_10_to_13(self.isbn_10)

        return super().save(*args, **kwargs)


def isbn_10_to_13(isbn_10):
    ''' convert an isbn 10 into an isbn 13 '''
    isbn_10 = re.sub(r'[^0-9X]', '', isbn_10)
    # drop the last character of the isbn 10 number (the original checkdigit)
    converted = isbn_10[:9]
    # add "978" to the front
    converted = '978' + converted
    # add a check digit to the end
    # multiply the odd digits by 1 and the even digits by 3 and sum them
    try:
        checksum = sum(int(i) for i in converted[::2]) + \
               sum(int(i) * 3 for i in converted[1::2])
    except ValueError:
        return None
    # add the checksum mod 10 to the end
    checkdigit = checksum % 10
    if checkdigit != 0:
        checkdigit = 10 - checkdigit
    return converted + str(checkdigit)


def isbn_13_to_10(isbn_13):
    ''' convert isbn 13 to 10, if possible '''
    if isbn_13[:3] != '978':
        return None

    isbn_13 = re.sub(r'[^0-9X]', '', isbn_13)

    # remove '978' and old checkdigit
    converted = isbn_13[3:-1]
    # calculate checkdigit
    # multiple each digit by 10,9,8.. successively and sum them
    try:
        checksum = sum(int(d) * (10 - idx) for (idx, d) in enumerate(converted))
    except ValueError:
        return None
    checkdigit = checksum % 11
    checkdigit = 11 - checkdigit
    if checkdigit == 10:
        checkdigit = 'X'
    return converted + str(checkdigit)

bookwyrm/models/connector.py
''' manages interfaces with external sources of book data '''
from django.db import models
from bookwyrm.connectors.settings import CONNECTORS

from .base_model import BookWyrmModel


ConnectorFiles = models.TextChoices('ConnectorFiles', CONNECTORS)
class Connector(BookWyrmModel):
    ''' book data source connectors '''
    identifier = models.CharField(max_length=255, unique=True)
    priority = models.IntegerField(default=2)
    name = models.CharField(max_length=255, null=True, blank=True)
    local = models.BooleanField(default=False)
    connector_file = models.CharField(
        max_length=255,
        choices=ConnectorFiles.choices
    )
    api_key = models.CharField(max_length=255, null=True, blank=True)

    base_url = models.CharField(max_length=255)
    books_url = models.CharField(max_length=255)
    covers_url = models.CharField(max_length=255)
    search_url = models.CharField(max_length=255, null=True, blank=True)

    politeness_delay = models.IntegerField(null=True, blank=True) #seconds
    max_query_count = models.IntegerField(null=True, blank=True)
    # how many queries executed in a unit of time, like a day
    query_count = models.IntegerField(default=0)
    # when to reset the query count back to 0 (ie, after 1 day)
    query_count_expiry = models.DateTimeField(auto_now_add=True, blank=True)

    class Meta:
        ''' check that there's code to actually use this connector '''
        constraints = [
            models.CheckConstraint(
                check=models.Q(connector_file__in=ConnectorFiles),
                name='connector_file_valid'
            )
        ]

    def __str__(self):
        return "{} ({})".format(
            self.identifier,
            self.id,
        )

bookwyrm/templates/about.html
{% extends 'layout.html' %}
{% block content %}

<div class="columns">
    <div class="column block">
        {% include 'snippets/about.html' %}
    </div>

    <div class="column block">
        <h2 class="title">Code of Conduct</h2>
        <div class="content">
            {{ site.code_of_conduct | safe }}
        </div>
    </div>
</div>
{% endblock %}

bookwyrm/templates/direct_messages.html
{% extends 'layout.html' %}
{% block content %}

<div class="block">
    <h1 class="title">Direct Messages</h1>

    {% if not activities %}
    <p>You have no messages right now.</p>
    {% endif %}
    {% for activity in activities %}
    <div class="block">
    {% include 'snippets/status.html' with status=activity %}
    </div>
    {% endfor %}

    <nav class="pagination" role="navigation" aria-label="pagination">
        {% if prev %}
        <p class="pagination-previous">
            <a href="{{ prev }}">
                <span class="icon icon-arrow-left"></span>
                Previous
            </a>
        </p>
        {% endif %}

        {% if next %}
        <p class="pagination-next">
            <a href="{{ next }}">
                Next
                <span class="icon icon-arrow-right"></span>
            </a>
        </p>
        {% endif %}
    </nav>
</div>

{% endblock %}

bookwyrm/templates/edit_book.html
{% extends 'layout.html' %}
{% load humanize %}
{% block content %}
<div class="block">
    <div class="level">
        <h1 class="title level-left">
            Edit "{{ book.title }}"
        </h1>
        <div class="level-right">
            <a href="/book/{{ book.id }}">
                <span class="edit-link icon icon-close">
                    <span class="is-sr-only">Close</span>
                </span>
            </a>
        </div>
    </div>
    <div>
        <p>Added: {{ book.created_date | naturaltime }}</p>
        <p>Updated: {{ book.updated_date | naturaltime }}</p>
    </div>
</div>

{% if login_form.non_field_errors %}
<div class="block">
    <p class="notification is-danger">{{ login_form.non_field_errors }}</p>
</div>
{% endif %}

<form class="block" name="edit-book" action="/edit-book/{{ book.id }}" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="block">
        <h2 class="title is-4">Data sync
            <p class="subtitle is-6">If sync is enabled, any changes will be over-written</p>
        </h2>
        <div class="columns">
            <div class="column is-narrow">
                <label class="checkbox" for="id_sync"><input class="checkbox" type="checkbox" name="sync" id="id_sync"> Sync</label>
            </div>
            <div class="column is-narrow">
                <label class="checkbox" for="id_sync_cover"><input class="checkbox" type="checkbox" name="sync_cover" id="id_sync_cover"> Sync cover</label>
            </div>
        </div>
    </div>

    <div class="columns">
        <div class="column">
            <h2 class="title is-4">Metadata</h2>
            <p class="fields is-grouped"><label class="label"for="id_title">Title:</label> {{ form.title }} </p>
            {% for error in form.title.errors %}
            <p class="help is-danger">{{ error | escape }}</p>
            {% endfor %}
            <p class="fields is-grouped"><label class="label"for="id_sort_title">Sort title:</label> {{ form.sort_title }} </p>
            {% for error in form.sort_title.errors %}
            <p class="help is-danger">{{ error | escape }}</p>
            {% endfor %}
            <p class="fields is-grouped"><label class="label"for="id_subtitle">Subtitle:</label> {{ form.subtitle }} </p>
            {% for error in form.subtitle.errors %}
            <p class="help is-danger">{{ error | escape }}</p>
            {% endfor %}
            <p class="fields is-grouped"><label class="label"for="id_description">Description:</label> {{ form.description }} </p>
            {% for error in form.description.errors %}
            <p class="help is-danger">{{ error | escape }}</p>
            {% endfor %}
            <p class="fields is-grouped"><label class="label"for="id_series">Series:</label> {{ form.series }} </p>
            {% for error in form.series.errors %}
            <p class="help is-danger">{{ error | escape }}</p>
            {% endfor %}
            <p class="fields is-grouped"><label class="label"for="id_series_number">Series number:</label> {{ form.series_number }} </p>
            {% for error in form.series_number.errors %}
            <p class="help is-danger">{{ error | escape }}</p>
            {% endfor %}
            <p class="fields is-grouped"><label class="label"for="id_first_published_date">First published date:</label> {{ form.first_published_date }} </p>
            {% for error in form.first_published_date.errors %}
            <p class="help is-danger">{{ error | escape }}</p>
            {% endfor %}
            <p class="fields is-grouped"><label class="label"for="id_published_date">Published date:</label> {{ form.published_date }} </p>
            {% for error in form.published_date.errors %}
            <p class="help is-danger">{{ error | escape }}</p>
            {% endfor %}
        </div>

        <div class="column">
            <div class="columns">
                <div class="column is-narrow">
                    {% include 'snippets/book_cover.html' with book=book size="small" %}
                </div>
                <div class="column is-narrow">
                    <div class="block">
                        <h2 class="title is-4">Cover</h2>
                        <p>{{ form.cover }} </p>
                        {% for error in form.cover.errors %}
                        <p class="help is-danger">{{ error | escape }}</p>
                        {% endfor %}
                    </div>
                </div>
            </div>

            <div class="block">
                <h2 class="title is-4">Physical Properties</h2>
                <p class="fields is-grouped"><label class="label"for="id_physical_format">Format:</label> {{ form.physical_format }} </p>
                {% for error in form.physical_format.errors %}
                <p class="help is-danger">{{ error | escape }}</p>
                {% endfor %}
                {% for error in form.physical_format.errors %}
                <p class="help is-danger">{{ error | escape }}</p>
                {% endfor %}

                <p class="fields is-grouped"><label class="label"for="id_pages">Pages:</label> {{ form.pages }} </p>
                {% for error in form.pages.errors %}
                <p class="help is-danger">{{ error | escape }}</p>
                {% endfor %}
            </div>

            <div class="block">
                <h2 class="title is-4">Book Identifiers</h2>
                <p class="fields is-grouped"><label class="label"for="id_isbn_13">ISBN 13:</label> {{ form.isbn_13 }} </p>
                {% for error in form.isbn_13.errors %}
                <p class="help is-danger">{{ error | escape }}</p>
                {% endfor %}
                <p class="fields is-grouped"><label class="label"for="id_isbn_10">ISBN 10:</label> {{ form.isbn_10 }} </p>
                {% for error in form.isbn_10.errors %}
                <p class="help is-danger">{{ error | escape }}</p>
                {% endfor %}
                <p class="fields is-grouped"><label class="label"for="id_openlibrary_key">Openlibrary key:</label> {{ form.openlibrary_key }} </p>
                {% for error in form.openlibrary_key.errors %}
                <p class="help is-danger">{{ error | escape }}</p>
                {% endfor %}
                <p class="fields is-grouped"><label class="label"for="id_librarything_key">Librarything key:</label> {{ form.librarything_key }} </p>
                {% for error in form.librarything_key.errors %}
                <p class="help is-danger">{{ error | escape }}</p>
                {% endfor %}
                <p class="fields is-grouped"><label class="label"for="id_goodreads_key">Goodreads key:</label> {{ form.goodreads_key }} </p>
                {% for error in form.goodreads_key.errors %}
                <p class="help is-danger">{{ error | escape }}</p>
                {% endfor %}
            </div>
        </div>
    </div>

    <div class="block">
        <button class="button is-primary" type="submit">Save</button>
        <a class="button" href="/book/{{ book.id }}">Cancel</a>
    </div>
</form>

{% endblock %}

bookwyrm/templates/editions.html
{% extends 'layout.html' %}
{% load bookwyrm_tags %}
{% block content %}
<div class="block">
    <h1 class="title">Editions of <a href="/book/{{ work.id }}">"{{ work.title }}"</a></h1>

    {% include 'snippets/book_tiles.html' with books=editions %}
</div>
{% endblock %}

bookwyrm/templates/error.html
{% extends 'layout.html' %}
{% block content %}

<div class="block">
    <h1 class="title">Server Error</h1>
    <p>Something went wrong! Sorry about that.</p>
</div>

{% endblock %}

bookwyrm/templates/following.html
{% extends 'layout.html' %}
{% load bookwyrm_tags %}
{% block content %}
<div class="block">
    <h1 class="title">
        Users following
        {% if is_self %}you
        {% else %}
        {% include 'snippets/username.html' with user=user %}
        {% endif %}
    </h1>
</div>

{% include 'snippets/user_header.html' with user=user %}

<div class="block">
    <h2 class="title">Following</h2>
    {% for follower in user.following.all %}
    <div class="block">
        <div class="field is-grouped">
            <div class="control">
                {% include 'snippets/avatar.html' with user=follower %}
            </div>
            <div class="control">
                {% include 'snippets/username.html' with user=follower show_full=True  %}
            </div>
            <div class="control">
                {% include 'snippets/follow_button.html' with user=follower %}
            </div>
        </div>
    </div>
    {% endfor %}
    {% if not following.count %}
    <div>No one is following {{ user|username }}</div>
    {% endif %}
</div>

{% endblock %}

bookwyrm/templates/import.html
{% extends 'layout.html' %}
{% load humanize %}
{% block content %}
<div class="block">
    <h1 class="title">Import Books from GoodReads</h1>
    <form name="import" action="/import-data/" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="field">
            {{ import_form.as_p }}
        </div>
        <div class="field">
            <label class="label">
                <input type="checkbox" name="include_reviews" checked> Include reviews
            </label>
        </div>
        <div class="field">
            <label class="label">
                <p>Privacy setting for imported reviews:</p>
                {% include 'snippets/privacy_select.html' with no_label=True %}
            </label>
        </div>
        <button class="button is-primary" type="submit">Import</button>
    </form>
    <p>
    Imports are limited in size, and only the first {{ limit }} items will be imported.
</div>

<div class="content block">
    <h2 class="title">Recent Imports</h2>
    {% if not jobs %}
    <p>No recent imports</p>
    {% endif %}
    <ul>
        {% for job in jobs %}
            <li><a href="/import-status/{{ job.id }}">{{ job.created_date | naturaltime }}</a></li>
        {% endfor %}
    </ul>
</div>
{% endblock %}

bookwyrm/templates/notfound.html
{% extends 'layout.html' %}
{% block content %}

<div class="block">
    <h1 class="title">Not Found</h1>
    <p>The page your requested doesn't seem to exist!</p>
</div>

{% endblock %}